services:
  - type: web
    name: privacy-app
    env: node
    buildCommand: npm run build  # Render will automatically handle this
    startCommand: npx serve build  # Serve the app from the 'build' directory
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --no-experimental-fetch
    healthCheckPath: /
    autoDeploy: true
